name: Update Unciv Atlas

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: update-unciv-atlas
  cancel-in-progress: true

jobs:
  update:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Optimize images
        run: |
          oxipng_url=$(curl -sL https://api.github.com/repos/shssoichiro/oxipng/releases/latest | grep -o "http.*x86_64-unknown-linux-gnu.tar.gz")
          wget -O oxipng.tar.gz "$oxipng_url"
          tar -xvzf oxipng.tar.gz
          rm oxipng.tar.gz

          oxipng_file=$(find oxipng* -type f -name oxipng | head -1)

          find Images* -type f -iname "*.png" -print0 | \
            xargs -0 -r "$oxipng_file" --opt max --strip all --alpha

          rm -rf oxipng*

      - name: Download Unciv
        run: |
          curl -L \
            -o Unciv.jar \
            https://github.com/yairm210/Unciv/releases/latest/download/Unciv.jar

      - name: Generate atlas
        run: |
          java -jar Unciv.jar mod-ci

      - name: Remove temporary files
        run: |
          rm -f Unciv.jar

      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add game.png game.atlas Atlases.json

          if git diff --cached --quiet; then
            echo "No atlas changes"
          else
            git commit -m "Update Unciv texture atlas"
            git pull --rebase origin master
            git push
          fi
